Add CredentialName and GoogleCloud fields in ClusterUserAuth spec
bytebuilders/resource-model pull request #71
Opened 2023-06-20 05:54 UTC by Shaad7

Signed-off-by: Masudur Rahman <masud@appscode.com>

2023-06-20 06:13 UTC, masudur-rahman requested changes

2023-06-20 06:13 UTC, masudur-rahman commented on apis/cluster/v1alpha1/cluster_user_auth_types.go
> +	GoogleCloud    *GoogleCloudCredential `json:"googleCloud,omitempty" protobuf:"bytes,16,opt,name=googleCloud"`
Keep both google credential side by side

2023-06-20 06:13 UTC, masudur-rahman commented on apis/cluster/v1alpha1/cluster_user_auth_types.go
> +	CredentialName string                 `json:"credentialName,omitempty" protobuf:"bytes,15,opt,name=credentialName"`
and the credential name in the last

2023-06-20 06:25 UTC, Shaad7 commented on apis/cluster/v1alpha1/cluster_user_auth_types.go
> +	GoogleCloud    *GoogleCloudCredential `json:"googleCloud,omitempty" protobuf:"bytes,16,opt,name=googleCloud"`
Updated

2023-06-20 06:25 UTC, Shaad7 commented on apis/cluster/v1alpha1/cluster_user_auth_types.go
> +	CredentialName string                 `json:"credentialName,omitempty" protobuf:"bytes,15,opt,name=credentialName"`
Updated

2023-06-26 03:59 UTC, masudur-rahman approved these changes

2023-06-26 04:00 UTC, merged